spring:
  dataSource:
    url: jdbc:mysql://localhost/merikuri
    username: user
    password: password
    sql-script-encoding: utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: NON_NULL
mybatis:
  mapper-locations: classpath*:mybatis/xml/*.xml